server:
  port: 8080
spring:
  application:
    name: model-server
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
async:
  pool:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 10000
